[package]
name = "echo-server-karin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }

[dependencies.uuid]
version = "0.8"
features = ["v4"]